

package practico6;

import java.util.TreeSet;


public class DeTodoSA extends javax.swing.JFrame {

     public static TreeSet<Producto> listaProductos= new TreeSet<>();
    
    public DeTodoSA() {
        initComponents();
        cargarProductos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jMAdmi = new javax.swing.JMenu();
        jMProductos = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMRubro = new javax.swing.JMenuItem();
        jMNombre = new javax.swing.JMenuItem();
        jMPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jMAdmi.setText("Administracion");

        jMProductos.setText("Productos");
        jMProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProductosActionPerformed(evt);
            }
        });
        jMAdmi.add(jMProductos);

        jMenu.add(jMAdmi);

        jMConsultas.setText("Consultas");

        jMRubro.setText("Por Rubro");
        jMRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRubroActionPerformed(evt);
            }
        });
        jMConsultas.add(jMRubro);

        jMNombre.setText("Por Nombre");
        jMNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNombreActionPerformed(evt);
            }
        });
        jMConsultas.add(jMNombre);

        jMPrecio.setText("Por Precio");
        jMPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPrecioActionPerformed(evt);
            }
        });
        jMConsultas.add(jMPrecio);

        jMenu.add(jMConsultas);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNombreActionPerformed
        // TODO add your handling code here:
       Escritorio.removeAll();
       Escritorio.repaint();
       BusquedaPorNombre bpn=new BusquedaPorNombre();
       bpn.setVisible(true);
       Escritorio.add(bpn);
       Escritorio.moveToFront(bpn);
       
       
    }//GEN-LAST:event_jMNombreActionPerformed

    private void jMProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProductosActionPerformed
        // TODO add your handling code here:
         Escritorio.removeAll();
       Escritorio.repaint();
       GestiondeProductos gdp=new GestiondeProductos();
       gdp.setVisible(true);
       Escritorio.add(gdp);
       Escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jMProductosActionPerformed

    private void jMRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRubroActionPerformed
        // TODO add your handling code here:
         Escritorio.removeAll();
       Escritorio.repaint();
       ProductosporRubro ppr=new ProductosporRubro();
       ppr.setVisible(true);
       Escritorio.add(ppr);
       Escritorio.moveToFront(ppr);
    }//GEN-LAST:event_jMRubroActionPerformed

    private void jMPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPrecioActionPerformed
        // TODO add your handling code here:
         Escritorio.removeAll();
       Escritorio.repaint();
       ListadoporPrecio lpp=new ListadoporPrecio();
       lpp.setVisible(true);
       Escritorio.add(lpp);
       Escritorio.moveToFront(lpp);
    }//GEN-LAST:event_jMPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodoSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodoSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMAdmi;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMNombre;
    private javax.swing.JMenuItem jMPrecio;
    private javax.swing.JMenuItem jMProductos;
    private javax.swing.JMenuItem jMRubro;
    private javax.swing.JMenuBar jMenu;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
    
        listaProductos.add(new Producto(10,"azucar x 1kg",180.76,5,Categoria.COMESTIBLE));
        listaProductos.add(new Producto(1234, "fideos",200,20,Categoria.COMESTIBLE));
        listaProductos.add(new Producto(322, "Perfume para bebes",1400, 4, Categoria.PERFUMERIA));
        listaProductos.add(new Producto(45,"Lavandina",400,40, Categoria.LIMPIEZA));
        
    }
}
