
package practico6;

import javax.swing.table.DefaultTableModel;




public class ProductosporRubro extends javax.swing.JInternalFrame {
 private DefaultTableModel modelo= new DefaultTableModel();


    
    public boolean isCellEditable(int f, int c){
        return false;
    }
    

    public ProductosporRubro() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRubro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos1 = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Listado de Productos por Rubro");

        jLabel2.setText("Elija rubro:");

        jRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new Categoria[] { Categoria.COMESTIBLE,Categoria.LIMPIEZA,Categoria.PERFUMERIA}));
        jRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRubroActionPerformed(evt);
            }
        });

        jTProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRubroActionPerformed
        // TODO add your handling code here:
        
        Categoria encontrado = (Categoria) jRubro.getSelectedItem();
        borrarFilas();
        for   (Producto encontrar : DeTodoSA.listaProductos){
        if(encontrar.getRubro().equals(encontrado)){
        modelo.addRow(new Object[]{
            encontrar.getCodigo(),
            encontrar.getDescripcion(),
            encontrar.getPrecio(),
            encontrar.getStock()           
            });
        
            }  
        }   
    }//GEN-LAST:event_jRubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<Categoria> jRubro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProductos1;
    // End of variables declaration//GEN-END:variables

public void armarCabecera(){
   modelo.addColumn("Codigo");
   modelo.addColumn("Descripcion");
   modelo.addColumn("Precio");
   modelo.addColumn("Stock");
   jTProductos1.setModel(modelo);
   }
private void borrarFilas(){
   int filas=jTProductos1.getRowCount()-1;
       for(int f=filas;f>=0;f--){
           modelo.removeRow(f);
       }
   }
}
